baseurl:
url: "http://hankewins.com/"
#url: "/"
name: Hankewins's Blog
author: Hankewins
email: hakewins@gmail.com
permalink: weblog/:title/
markdown: kramdown
highlighter: pygments
JB :
  categories_path: categories.html
